
server:
  port: 8090

spring:
    redis:
#        host: 192.168.153.185
        host: 127.0.0.1
        port: 6379
        database: 0
        password: 123456a?
        timeout: 60
        pool:
          max-active: 8
          max-wait: -1
          max-idle: 8
          min-idle: 0
    datasource:
        name: test
#        url: jdbc:mysql://127.0.0.1:3306/mytest
        url: jdbc:mysql://47.104.182.63:3306/home
        username: root
        password: mylove093196
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
    thymeleaf:
        prefix: classpath:/views/
        suffix: .html
        mode: HTML5
        encoding: UTF-8
        content-type: text/html
        cache: false

mybatis:
  mapper-locations: classpath:Mapper/*.xml
  type-aliases-package: com.chengym.home.Bean

#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
logging:
  #配置日志文件路径
  level:
    xatu.zsl: debug #不同目录下的日志可配置不同级别
    org.springfromework.web: info
    org.hibernate: error
  #采用相对路径方式将日志文件输出到【log\myspringboot.log】
  file: ./log/myspringboot.log
  config: classpath:logback.xml